### ISSUE TITLE
too long lines of code

### ISSUE THREAD

**Issue by meni181818** [mikepet74/List_of_duties#14]
https://github.com/mikepet74/List_of_duties/blob/d3bc888400d622d720cb1fb367ffae07e4f439dd/Project1/Main.c#L18
"The preferred limit on the length of a single line is 80 columns." ([linux kernel coding style](https://www.kernel.org/doc/html/latest/process/coding-style.html#breaking-long-lines-and-strings))

**Comment by mikepet74** [comment]
Done
