### ISSUE TITLE
it's not really doing anything to the string, and even if it was doing - it was very dangerous 

### ISSUE THREAD

**Issue by meni181818** [mikepet74/List_of_duties#8]
https://github.com/mikepet74/List_of_duties/blob/c66bfdd67324e1bf349374100324eea1747c91ee/Project1/General.c#L91
you just moving the local pointer inside the function.
there is a way to move the original char *...
but if you do so - you might get really bad errors when you trying to free() the new position of your pointer..

**Comment by mikepet74** [comment]
fixed
